#!/usr/bin/env python3
"""
Quality Evaluation Test Suite for Medical Articles Checker

Tests:
1. Section parser correctness on synthetic articles
2. Enhanced checker accuracy vs ground truth annotations
3. Comparison: enhanced vs original checker (regression/improvement)
4. False positive / false negative analysis
5. Edge cases (empty text, no sections, short articles)

Run: pytest tests/test_quality.py -v
"""

import json
import sys
import os
import pytest
from pathlib import Path

# Add parent dir to path so we can import our modules
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from section_parser import SectionParser, get_expected_sections
from enhanced_checker import EnhancedChecker, CheckResult


# ===========================================================================
# Fixtures
# ===========================================================================

@pytest.fixture
def parser():
    return SectionParser()


@pytest.fixture
def checker():
    """Enhanced checker using the upgraded checklists."""
    checklist_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'checklists')
    return EnhancedChecker(checklist_dir=checklist_dir)


# ===========================================================================
# Synthetic article text for testing
# ===========================================================================

WELL_STRUCTURED_RCT = """
A Randomized Controlled Trial of Drug X versus Placebo for Treatment of Condition Y

Abstract
Objective: To evaluate the efficacy and safety of Drug X compared to placebo in patients
with Condition Y. Setting: University Hospital, Department of Internal Medicine.
Main outcome: Reduction in symptom score at 12 weeks.
Methods: Double-blind, parallel-group randomized controlled trial.
Results: Drug X significantly reduced symptom scores compared to placebo (p<0.001).
Conclusions: Drug X is effective and well-tolerated for Condition Y.

Introduction
Condition Y affects approximately 5% of the adult population worldwide. Previous studies
have suggested that the pathophysiology involves pathway Z. The rationale for testing
Drug X is based on its mechanism of action targeting pathway Z. Current evidence from
observational studies is limited. We hypothesized that Drug X would reduce symptom
scores by at least 30% compared to placebo. The aim of this study was to evaluate
the efficacy and safety of Drug X in a rigorous trial design.

Methods

Trial design
This was a superiority, double-blind, parallel group, randomized controlled trial with
a 1:1 allocation ratio. The trial design followed CONSORT guidelines.

Participants
Eligibility criteria included: adults aged 18-65 with confirmed diagnosis of Condition Y.
Inclusion criteria were: symptom score >5, stable condition for at least 4 weeks.
Exclusion criteria were: pregnancy, severe comorbidities, allergy to Drug X.
The study was conducted at University Hospital, a tertiary care medical center.

Interventions
Patients in the intervention group received Drug X 100mg per day orally for 12 weeks.
The control group received matching placebo with identical appearance. The treatment
regimen was identical in both arms except for the active ingredient.

Outcomes
The primary outcome was change in symptom score at 12 weeks measured by the
validated Symptom Assessment Scale. Secondary endpoints included quality of life
score and adverse events.

Sample size
Sample size calculation was based on detecting a 30% difference in symptom scores.
With 80% statistical power and alpha of 0.05, we calculated that 120 participants
were needed (60 per group). Power analysis was performed using G*Power.

Randomization
The randomization sequence was generated by computer-generated random numbers
using a random number generator. Permuted blocks of variable block size (4 and 6)
were used. Stratified randomization was performed by age group and disease severity.

Allocation concealment
Allocation concealment was maintained using sequentially numbered, opaque, sealed
envelopes prepared by an independent pharmacist. Central randomization was performed
via telephone randomization service.

Blinding
Participants, investigators, and outcome assessors were blinded (triple-blind).
The placebo tablets were identical in appearance, taste, and packaging to Drug X
(matching placebo).

Statistical analysis
Statistical analysis was performed using SPSS v26. The primary outcome was compared
between groups using an independent samples t-test. Chi-square test was used for
categorical variables. Mann-Whitney U test was used for non-normally distributed data.
Logistic regression was used for binary outcomes. Subgroup analysis was pre-specified
for age groups and disease severity. Sensitivity analysis was performed using
per-protocol analysis population. All analyses followed the intention-to-treat principle.

Results

Participant flow
Between January 2023 and December 2023, 200 patients were screened. 130 were
randomly assigned: 65 to Drug X and 65 to placebo (CONSORT diagram, Figure 1).
The flow diagram shows the participant flow through the trial.

Losses and follow-up
Five patients in the Drug X group withdrew due to adverse events. Three patients
in the placebo group were lost to follow-up. One patient discontinued the study
medication but was included in the intention-to-treat analysis.

Recruitment
The recruitment period was from January 2023 to June 2023. The follow-up period
extended to December 2023. Enrollment was completed when the target sample size
was reached.

Baseline characteristics
Baseline demographics are presented in Table 1. Patient characteristics were balanced
between groups. Mean age was 45 years; 55% were female. Clinical characteristics
at baseline were similar across groups.

Numbers analyzed
The intention-to-treat population included all 130 randomized patients (ITT). The
per-protocol analysis included 122 patients who completed the full analysis set.

Primary outcome
Drug X significantly reduced symptom scores: mean difference -3.5 points
(95% CI: -4.8 to -2.2, p<0.001). The treatment effect corresponded to a
between-group difference of 35%. The hazard ratio for symptom resolution was
1.8 (95% CI 1.2-2.7). The p value was significant after Bonferroni correction.

Binary outcomes
For the binary outcome of clinical response (>=50% improvement): relative risk 2.1
(95% CI 1.4-3.1), absolute risk reduction 25%, number needed to treat (NNT) = 4.

Additional analyses
Pre-specified subgroup analysis showed consistent treatment effects across age groups.
Sensitivity analysis using per-protocol results confirmed the primary findings.
Exploratory analysis of biomarker levels showed dose-response relationship.

Adverse events
Adverse events were reported in 20% of Drug X group and 15% of placebo group.
Serious adverse events occurred in 2 patients (Drug X) and 1 patient (placebo).
The safety profile was acceptable. Treatment-related adverse effects included
nausea (8%), headache (5%), and dizziness (3%). No toxicity was observed.

Discussion

Our findings suggest that Drug X is effective for Condition Y. These results indicate
a clinically meaningful benefit. The treatment effect is consistent with previous
observational studies. In line with prior pharmacological research, the mechanism of
action supports the observed efficacy.

Limitations
This study has several limitations. First, the sample size was relatively small.
Second, the follow-up period was limited to 12 weeks. Results should be interpreted
with caution due to the single-center design, which is a potential bias. Weaknesses
include the lack of long-term safety data.

The generalizability of our findings may be limited to patients similar to our study
population. External validity should be assessed in broader populations.

In conclusion, Drug X at 100mg daily significantly reduces symptoms of Condition Y
compared to placebo with an acceptable risk-benefit profile. The implications for
clinical practice include consideration of Drug X as a first-line treatment option.
Benefits and harms should be carefully weighed.

Trial registration
This trial was registered at ClinicalTrials.gov (NCT04123456) before enrollment.
The trial registration number is NCT04123456.

Protocol
The study protocol was approved by the institutional review board and has been
published separately (Trial protocol reference XYZ).

Funding
This work was funded by Research Foundation Grant No. 12345. The role of the funder
was limited to financial support with no influence on study design. The authors declare
no competing interests.
"""


POORLY_REPORTED_RCT = """
Hydroxychloroquine and azithromycin as a treatment of COVID-19

In this study we tested hydroxychloroquine for COVID-19 treatment.
Twenty patients received hydroxychloroquine and 16 were controls.
Patients were included in the hospital.

We gave hydroxychloroquine 200mg three times daily for ten days.
Some patients also received azithromycin.

Results showed that hydroxychloroquine reduced viral load.
At day 6, 70% of treated patients were virologically cured
compared to 12.5% in the control group (p<0.001).

Side effects were minimal. One patient stopped treatment
due to nausea.

The findings show hydroxychloroquine is effective.
More studies are needed.

Funding was provided by the hospital.
"""


EMPTY_TEXT = ""

SHORT_TEXT = "This is a very short article about medicine."


# ===========================================================================
# Ground truth: what CONSORT items should be present in our test articles
# ===========================================================================

# For the WELL_STRUCTURED_RCT, these items should definitely be detected:
WELL_STRUCTURED_EXPECTED_PRESENT = {
    '1a',   # randomized trial in title
    '1b',   # structured abstract
    '2a',   # background/rationale
    '2b',   # objectives/hypotheses
    '3a',   # trial design
    '4a',   # eligibility criteria
    '4b',   # settings
    '5',    # interventions
    '6a',   # outcomes
    '7a',   # sample size
    '8a',   # randomization sequence
    '8b',   # type of randomisation
    '9',    # allocation concealment
    '10',   # implementation
    '11a',  # blinding
    '11b',  # similarity of interventions
    '12a',  # statistical methods
    '12b',  # additional analyses
    '13a',  # participant flow
    '13b',  # losses
    '14a',  # recruitment dates
    '14b',  # why trial ended
    '15',   # baseline data
    '16',   # numbers analysed
    '17a',  # outcomes/estimation
    '17b',  # binary outcomes
    '18',   # ancillary analyses
    '19',   # harms
    '20',   # limitations
    '21',   # generalisability
    '22',   # interpretation
    '23',   # registration
    '24',   # protocol
    '25',   # funding
}

# For the POORLY_REPORTED_RCT, these should be ABSENT:
POORLY_REPORTED_EXPECTED_ABSENT = {
    '3a',   # no trial design described
    '3b',   # no protocol changes
    '6b',   # no outcome changes
    '7a',   # no sample size calc
    '7b',   # no interim analysis
    '8a',   # no randomization sequence
    '8b',   # no randomization type
    '9',    # no allocation concealment
    '11a',  # no blinding
    '11b',  # no placebo described
    '12a',  # no statistical methods detailed
    '12b',  # no subgroup analyses
    '13a',  # no CONSORT flow
    '13b',  # no losses reported properly
    '14a',  # no recruitment dates
    '16',   # no ITT/per-protocol
    '17b',  # no binary outcome measures
    '18',   # no ancillary analyses
    '20',   # no limitations
    '21',   # no generalisability
    '23',   # no registration
    '24',   # no protocol access
}


# ===========================================================================
# Test: Section Parser
# ===========================================================================

class TestSectionParser:

    def test_parse_well_structured(self, parser):
        sections = parser.parse(WELL_STRUCTURED_RCT)
        summary = parser.get_section_summary(sections)

        assert summary['has_abstract'], "Should detect abstract"
        assert 'methods' in sections, "Should detect methods"
        assert 'results' in sections, "Should detect results"
        assert 'discussion' in sections, "Should detect discussion"

    def test_imrad_complete(self, parser):
        sections = parser.parse(WELL_STRUCTURED_RCT)
        summary = parser.get_section_summary(sections)
        # May not detect 'introduction' if heading says 'Introduction'
        # but should detect most IMRaD sections
        detected = set(sections.keys()) - {'full_text'}
        assert len(detected) >= 4, f"Should find at least 4 sections, found: {detected}"

    def test_methods_subsections(self, parser):
        sections = parser.parse(WELL_STRUCTURED_RCT)
        if 'methods' in sections:
            methods = sections['methods']
            sub_names = [s.name for s in methods.subsections]
            # Should find at least some of: participants, randomization, blinding, etc.
            assert len(sub_names) >= 2, f"Should find methods subsections, found: {sub_names}"

    def test_empty_text(self, parser):
        sections = parser.parse(EMPTY_TEXT)
        assert 'full_text' in sections
        assert len(sections) >= 1

    def test_short_text(self, parser):
        sections = parser.parse(SHORT_TEXT)
        assert 'full_text' in sections

    def test_poorly_structured(self, parser):
        sections = parser.parse(POORLY_REPORTED_RCT)
        # Should still return full_text even without clear headings
        assert 'full_text' in sections

    def test_section_aliases(self):
        """Test that section alias mapping works."""
        secs = get_expected_sections('Methods - Blinding')
        assert 'methods' in secs

        secs = get_expected_sections('Results - Harms')
        assert 'results' in secs

        secs = get_expected_sections('Nonexistent Section')
        assert 'full_text' in secs


# ===========================================================================
# Test: Enhanced Checker Quality
# ===========================================================================

class TestEnhancedCheckerQuality:

    def test_well_structured_high_compliance(self, checker):
        """A well-structured RCT should score >80% compliance."""
        result = checker.check(WELL_STRUCTURED_RCT, 'CONSORT')

        assert result.weighted_score > 70, (
            f"Well-structured RCT should score >70%, got {result.weighted_score}%"
        )
        assert result.simple_score > 70, (
            f"Simple score should be >70%, got {result.simple_score}%"
        )

    def test_well_structured_ground_truth(self, checker):
        """Check that specific items are detected as present."""
        result = checker.check(WELL_STRUCTURED_RCT, 'CONSORT')

        detected_present = set()
        for item in result.items:
            if item.verdict in ('present', 'partial'):
                detected_present.add(item.item_id)

        # At least 80% of expected-present items should be found
        expected = WELL_STRUCTURED_EXPECTED_PRESENT
        true_positives = detected_present & expected
        recall = len(true_positives) / len(expected)

        assert recall >= 0.80, (
            f"Recall too low: {recall:.0%}. "
            f"Missed: {expected - detected_present}"
        )

    def test_poorly_reported_low_compliance(self, checker):
        """A poorly reported study should score <50% compliance."""
        result = checker.check(POORLY_REPORTED_RCT, 'CONSORT')

        assert result.weighted_score < 50, (
            f"Poorly reported RCT should score <50%, got {result.weighted_score}%"
        )

    def test_poorly_reported_detects_absence(self, checker):
        """Items known to be absent should be detected as absent."""
        result = checker.check(POORLY_REPORTED_RCT, 'CONSORT')

        detected_absent = set()
        for item in result.items:
            if item.verdict in ('absent', 'explicitly_absent'):
                detected_absent.add(item.item_id)

        expected_absent = POORLY_REPORTED_EXPECTED_ABSENT
        true_negatives = detected_absent & expected_absent
        specificity = len(true_negatives) / len(expected_absent)

        assert specificity >= 0.70, (
            f"Specificity too low: {specificity:.0%}. "
            f"False positives on: {expected_absent - detected_absent}"
        )

    def test_empty_text_no_crash(self, checker):
        """Empty text should not crash."""
        result = checker.check(EMPTY_TEXT, 'CONSORT')
        assert result.weighted_score == 0
        assert result.total_items > 0

    def test_short_text_low_score(self, checker):
        """Very short text should score near zero."""
        result = checker.check(SHORT_TEXT, 'CONSORT')
        assert result.weighted_score < 20

    def test_section_awareness(self, checker):
        """Keywords found in the right section should score higher."""
        result = checker.check(WELL_STRUCTURED_RCT, 'CONSORT')

        section_matched_items = [i for i in result.items if i.section_match]
        fallback_items = [i for i in result.items if not i.section_match and i.matched_keywords]

        # Items matched in correct sections should have higher average confidence
        if section_matched_items and fallback_items:
            avg_section = sum(i.confidence for i in section_matched_items) / len(section_matched_items)
            avg_fallback = sum(i.confidence for i in fallback_items) / len(fallback_items)
            # We just check that section-matched are not worse than fallback
            assert avg_section >= avg_fallback * 0.8, (
                f"Section-matched items ({avg_section:.2f}) should not score "
                f"much lower than fallback ({avg_fallback:.2f})"
            )


# ===========================================================================
# Test: Evidence Snippets
# ===========================================================================

class TestEvidenceSnippets:

    def test_snippets_provided(self, checker):
        """Present items should include evidence snippets."""
        result = checker.check(WELL_STRUCTURED_RCT, 'CONSORT')

        present_items = [i for i in result.items if i.verdict == 'present']
        items_with_evidence = [i for i in present_items if i.evidence_snippets]

        # Most present items should have at least one evidence snippet
        if present_items:
            ratio = len(items_with_evidence) / len(present_items)
            assert ratio >= 0.7, (
                f"Only {ratio:.0%} of present items have evidence snippets"
            )


# ===========================================================================
# Test: Section Coverage Report
# ===========================================================================

class TestSectionCoverage:

    def test_section_coverage_keys(self, checker):
        """Section coverage should include main article sections."""
        result = checker.check(WELL_STRUCTURED_RCT, 'CONSORT')
        # Should have coverage for at least Methods, Results, Discussion
        keys = set(result.section_coverage.keys())
        assert len(keys) >= 3, f"Expected >=3 section groups, got: {keys}"

    def test_methods_coverage_detail(self, checker):
        """Well-structured RCT should have good Methods coverage."""
        result = checker.check(WELL_STRUCTURED_RCT, 'CONSORT')
        methods_coverage = result.section_coverage.get('Methods', 0)
        assert methods_coverage > 40, (
            f"Methods coverage should be >40%, got {methods_coverage}%"
        )


# ===========================================================================
# Test: Confidence Scoring
# ===========================================================================

class TestConfidenceScoring:

    def test_confidence_range(self, checker):
        """All confidence scores should be between 0 and 1."""
        result = checker.check(WELL_STRUCTURED_RCT, 'CONSORT')
        for item in result.items:
            assert 0.0 <= item.confidence <= 1.0, (
                f"Item {item.item_id} confidence {item.confidence} out of range"
            )

    def test_high_confidence_items(self, checker):
        """Items with many keyword matches should have high confidence."""
        result = checker.check(WELL_STRUCTURED_RCT, 'CONSORT')

        for item in result.items:
            if item.keyword_match_ratio >= 0.5 and item.section_match:
                assert item.confidence >= 0.5, (
                    f"Item {item.item_id}: matched {item.keyword_match_ratio:.0%} "
                    f"of keywords in correct section but confidence only {item.confidence:.0%}"
                )

    def test_verdict_consistency(self, checker):
        """Verdicts should be consistent with confidence scores."""
        result = checker.check(WELL_STRUCTURED_RCT, 'CONSORT')

        for item in result.items:
            if item.verdict == 'present':
                assert item.confidence >= 0.5, (
                    f"Item {item.item_id}: 'present' verdict but confidence "
                    f"only {item.confidence}"
                )
            elif item.verdict == 'absent':
                assert item.confidence < 0.6, (
                    f"Item {item.item_id}: 'absent' verdict but confidence "
                    f"{item.confidence}"
                )


# ===========================================================================
# Test: Report Generation
# ===========================================================================

class TestReportGeneration:

    def test_markdown_report(self, checker):
        result = checker.check(WELL_STRUCTURED_RCT, 'CONSORT')
        report = checker.generate_report(result, 'markdown')
        assert '# ' in report
        assert 'CONSORT' in report
        assert 'Weighted score' in report or 'weighted_score' in report

    def test_json_report(self, checker):
        result = checker.check(WELL_STRUCTURED_RCT, 'CONSORT')
        report = checker.generate_report(result, 'json')
        data = json.loads(report)
        assert 'weighted_score' in data
        assert 'items' in data
        assert len(data['items']) == result.total_items

    def test_text_report(self, checker):
        result = checker.check(WELL_STRUCTURED_RCT, 'CONSORT')
        report = checker.generate_report(result, 'text')
        assert 'FOUND' in report or 'MISSING' in report


# ===========================================================================
# Comparison: Enhanced vs Original (if original is available)
# ===========================================================================

class TestEnhancedVsOriginal:
    """
    These tests verify the enhanced checker is at least as good as the
    original, or better. They are designed to highlight specific
    improvements.
    """

    def test_no_generic_keyword_false_positives(self, checker):
        """
        The original checker marked item 1b as 'found' because 'background',
        'methods', 'results' appeared *somewhere* in the text. The enhanced
        checker should only match when these appear in the abstract context.
        """
        # Article with NO abstract but contains 'methods', 'results' elsewhere
        no_abstract_text = """
        A study about something.

        Methods
        We did some experiments. The methods were standard.

        Results
        We found some results. The background of the patients was varied.
        """
        result = checker.check(no_abstract_text, 'CONSORT')

        item_1b = next(i for i in result.items if i.item_id == '1b')
        # With enhanced keywords ('structured abstract', 'trial design', etc.),
        # this should NOT match strongly
        assert item_1b.confidence < 0.6, (
            f"Item 1b (structured abstract) should not be confident without "
            f"actual abstract structure. Got confidence: {item_1b.confidence}"
        )

    def test_distinguishes_well_vs_poorly_reported(self, checker):
        """
        The enhanced checker should produce a significantly higher score
        for the well-structured RCT than for the poorly reported one.
        """
        good_result = checker.check(WELL_STRUCTURED_RCT, 'CONSORT')
        poor_result = checker.check(POORLY_REPORTED_RCT, 'CONSORT')

        gap = good_result.weighted_score - poor_result.weighted_score
        assert gap >= 25, (
            f"Score gap between good and poor articles should be >=25 points. "
            f"Good: {good_result.weighted_score}, Poor: {poor_result.weighted_score}, "
            f"Gap: {gap}"
        )


if __name__ == '__main__':
    pytest.main([__file__, '-v', '--tb=short'])
